spring.application.name=tripnext

server.port=8080

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:54704/railway
spring.datasource.username=root
spring.datasource.password=MttpWFOYKPjmcvDLCxzGiutsdfcwdPqN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JDBC DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# THYMELEAF
spring.thymeleaf.cache=false

# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohitpani007@gmail.com
spring.mail.password=jssirrcketahpqth
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RAZORPAY CONFIGURATION
razorpay.key.id=rzp_test_SoUr1jQGbH76t6
razorpay.key.secret=pC9Yu8jDu0vDSfXB0oyrXQrz

# GEMINI AI CONFIGURATION
gemini.api.key=AIzaSyAVcVFWSWfTWCUKN4m-qCqrMx9a9u9nZ_c